// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAXq763PWh5q6JVHz4ZK9FskQPmqc1ZQw0',
    appId: '1:900726033511:web:e0571db61a9410e48958c2',
    messagingSenderId: '900726033511',
    projectId: 'scriba-v2',
    authDomain: 'scriba-v2.firebaseapp.com',
    storageBucket: 'scriba-v2.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAA2otZ2dvZeYkmG5D4UcRmpNU6F0dcHbo',
    appId: '1:900726033511:android:572eb4ebd06b66ae8958c2',
    messagingSenderId: '900726033511',
    projectId: 'scriba-v2',
    storageBucket: 'scriba-v2.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA6bBSUw4QbDY45CWtTA60fS50rFt4Nxu0',
    appId: '1:900726033511:ios:f86c0a2b00e4e7918958c2',
    messagingSenderId: '900726033511',
    projectId: 'scriba-v2',
    storageBucket: 'scriba-v2.appspot.com',
    iosClientId: '900726033511-c40jd44v74s3b4rethmbeepvdqs77dfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.scriba',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA6bBSUw4QbDY45CWtTA60fS50rFt4Nxu0',
    appId: '1:900726033511:ios:f86c0a2b00e4e7918958c2',
    messagingSenderId: '900726033511',
    projectId: 'scriba-v2',
    storageBucket: 'scriba-v2.appspot.com',
    iosClientId: '900726033511-c40jd44v74s3b4rethmbeepvdqs77dfa.apps.googleusercontent.com',
    iosBundleId: 'com.example.scriba',
  );
}
